# Generated by Django 5.2.2 on 2025-11-04 10:53

import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_value", models.FloatField()),
                ("y_value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CalculationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Без названия",
                        max_length=200,
                        verbose_name="Название расчета",
                    ),
                ),
                ("param_a", models.FloatField()),
                ("param_b", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "iterations",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество итераций"
                    ),
                ),
                (
                    "exec_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Время выполнения (сек)"
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Алгоритм"
                    ),
                ),
                (
                    "average_op",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Средняя относительная погрешность (%)",
                    ),
                ),
                (
                    "table_data",
                    models.TextField(
                        blank=True, null=True, verbose_name="Данные таблицы"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="post_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "calculation_snapshot",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Копия данных расчета"
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Алгоритм"
                    ),
                ),
                (
                    "a12",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="A12"
                    ),
                ),
                (
                    "a21",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="A21"
                    ),
                ),
                (
                    "iterations",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Итерации"
                    ),
                ),
                (
                    "exec_time",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "average_error",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Средняя погрешность",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("forum", "Создан вручную на форуме"),
                            ("calculation", "Создан из расчёта"),
                        ],
                        default="forum",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "calculation_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.calculationresult",
                        verbose_name="Результат расчёта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(max_length=1000, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="main.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="avatars/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default="Untitled")),
                ("solution", models.TextField(default="")),
                ("temperature", models.FloatField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "points",
                    models.ManyToManyField(related_name="tables", to="main.point"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="calculationresult",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="main.table",
            ),
        ),
    ]
