# Generated by Django 5.2.2 on 2025-08-11 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_image_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название алгоритма')),
                ('code', models.TextField(verbose_name='Код алгоритма')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание алгоритма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_algorithms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользовательский алгоритм',
                'verbose_name_plural': 'Пользовательские алгоритмы',
            },
        ),
    ]
