# Generated by Django 5.2.2 on 2025-11-03 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_image_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationresult',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='a12',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='A12'),
        ),
        migrations.AddField(
            model_name='post',
            name='a21',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='A21'),
        ),
        migrations.AddField(
            model_name='post',
            name='algorithm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Алгоритм'),
        ),
        migrations.AddField(
            model_name='post',
            name='average_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Средняя погрешность'),
        ),
        migrations.AddField(
            model_name='post',
            name='calculation_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Копия данных расчета'),
        ),
        migrations.AddField(
            model_name='post',
            name='exec_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AddField(
            model_name='post',
            name='iterations',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Итерации'),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('forum', 'Создан вручную на форуме'), ('calculation', 'Создан из расчёта')], default='forum', max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='table',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='main.table'),
        ),
        migrations.AlterField(
            model_name='post',
            name='calculation_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.calculationresult', verbose_name='Результат расчёта'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
